server:
  port: 8080

spring:
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mt_db
    username: mt_user
    password: mt_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
  flyway:
    enabled: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
app:
  jwt:
    secret: ${JWT_SECRET:dev-super-secret-change-me-please-32+chars}
    expirationSeconds: 3600
    refreshExpirationSeconds: 1209600
  seed:
    mohamedEmail: "${SEED_EMAIL:mohamed@example.com}"
    mohamedDisplayName: "${SEED_DISPLAY_NAME:Mohamed}"
    mohamedPassword: "${SEED_PASSWORD:StrongPass}"
    resetOnStart: true
logging:
  level:
    org.springframework.security: INFO
mediatracker:
  tmdb:
    apiKey: ${TMDB_API_KEY}
  rawg:
    apiKey: ${RAWG_API_KEY}